version: '3'
services:
  mvc:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
  db:
    image: mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=clubs
      #- MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=123@Password
    volumes:
      - db-data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    ports: 
      - 8080:80
volumes:
  db-data: